[package]
name = "myos-api"
edition.workspace = true
version.workspace = true

[dependencies]
zerocopy = { workspace = true }
nostdio = { path = "../../utils/nostdio", default-features = false }

[features]
std = []
