[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader_api = { workspace = true }
paste = { workspace = true }
pc-screen-font = { path = "../crates/pc-screen-font" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
