[package]
name = "allocator"
edition.workspace = true
version.workspace = true

[dependencies]
linked_list_allocator = { version = "0.10.5", default-features = false }
spin = { workspace = true }

[dev-dependencies]
assert_hex = { workspace = true }
